ERROR - 2024-03-27 00:21:07,824 - apiutil.py:120 -[apiutil:specification_yaml] - extract_data() missing 1 required positional argument: 'response'
ERROR - 2024-03-27 00:21:33,935 - apiutil.py:120 -[apiutil:specification_yaml] - extract_data() missing 1 required positional argument: 'response'
ERROR - 2024-03-27 00:21:53,694 - apiutil.py:120 -[apiutil:specification_yaml] - extract_data() missing 1 required positional argument: 'response'
ERROR - 2024-03-27 00:25:16,783 - apiutil.py:121 -[apiutil:specification_yaml] - extract_data() missing 1 required positional argument: 'response'
INFO - 2024-03-27 01:06:42,055 - apiutil.py:148 -[apiutil:extract_data] - 正则表达式提取到的参数:{'token': '6a227eAF603dcedADbbBedCa9DeaC'}
ERROR - 2024-03-27 01:06:42,056 - apiutil.py:124 -[apiutil:specification_yaml] - write_yaml_data() missing 1 required positional argument: 'file_path'
INFO - 2024-03-27 01:08:55,823 - apiutil.py:148 -[apiutil:extract_data] - 正则表达式提取到的参数:{'token': 'Db7cba5dcA4C2BA51b9BBcc51be52'}
INFO - 2024-03-27 01:10:00,434 - apiutil.py:148 -[apiutil:extract_data] - 正则表达式提取到的参数:{'token': 'a6a84c5EFc3ec7fAfA8AB8ec726f2'}
INFO - 2024-03-27 01:10:25,210 - apiutil.py:148 -[apiutil:extract_data] - 正则表达式提取到的参数:{'token': 'B05Ddd5d9cda52E3745c5aeEb6e6A'}
INFO - 2024-03-27 01:11:11,603 - apiutil.py:148 -[apiutil:extract_data] - 正则表达式提取到的参数:{'token': 'CAFEADD531cB93deB84dBE90B34F8'}
INFO - 2024-03-27 01:12:13,653 - apiutil.py:148 -[apiutil:extract_data] - 正则表达式提取到的参数:{'token': '1677F4eC4E73EdafAe66F8d47D8af'}
INFO - 2024-03-27 01:27:53,304 - apiutil.py:159 -[apiutil:extract_data] - json提取:{'token': '33FCcD086aE18Eb9B33DFCC94550b'}
INFO - 2024-03-27 01:27:59,942 - apiutil.py:159 -[apiutil:extract_data] - json提取:{'token': 'F59c619e4EEAcdaEAe4d3D1a86BaA'}
INFO - 2024-03-27 01:27:59,946 - apiutil.py:159 -[apiutil:extract_data] - json提取:{'token': 'a6DB4baF188dF02Ce25A1a4eD3f7E'}
ERROR - 2024-03-27 17:35:41,453 - apiutil.py:124 -[apiutil:specification_yaml] - HTTPConnectionPool(host='127.0.0.1', port=8787): Max retries exceeded with url: /dar/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C820239BC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
ERROR - 2024-03-27 17:36:17,242 - apiutil.py:124 -[apiutil:specification_yaml] - HTTPConnectionPool(host='127.0.0.1', port=8787): Max retries exceeded with url: /dar/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002C472939B48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
ERROR - 2024-03-27 17:37:52,033 - apiutil.py:124 -[apiutil:specification_yaml] - HTTPConnectionPool(host='127.0.0.1', port=8787): Max retries exceeded with url: /dar/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000024F94487D08>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
ERROR - 2024-03-27 17:40:24,145 - apiutil.py:125 -[apiutil:specification_yaml] - HTTPConnectionPool(host='127.0.0.1', port=8787): Max retries exceeded with url: /dar/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000141AB937BC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
ERROR - 2024-03-27 17:41:20,658 - apiutil.py:125 -[apiutil:specification_yaml] - HTTPConnectionPool(host='127.0.0.1', port=8787): Max retries exceeded with url: /dar/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018A44419A48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
ERROR - 2024-03-27 17:44:14,742 - apiutil.py:126 -[apiutil:specification_yaml] - HTTPConnectionPool(host='127.0.0.1', port=8787): Max retries exceeded with url: /dar/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000270CC7A4888>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
ERROR - 2024-03-27 17:44:23,845 - apiutil.py:126 -[apiutil:specification_yaml] - HTTPConnectionPool(host='127.0.0.1', port=8787): Max retries exceeded with url: /dar/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019A14D98848>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
ERROR - 2024-03-27 17:47:36,591 - apiutil.py:126 -[apiutil:specification_yaml] - HTTPConnectionPool(host='127.0.0.1', port=8787): Max retries exceeded with url: /dar/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001BEBD9F7C88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
ERROR - 2024-03-27 17:49:22,691 - apiutil.py:131 -[apiutil:specification_yaml] - HTTPConnectionPool(host='127.0.0.1', port=8787): Max retries exceeded with url: /dar/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BA5693508>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
ERROR - 2024-03-27 17:49:22,691 - apiutil.py:131 -[apiutil:specification_yaml] - HTTPConnectionPool(host='127.0.0.1', port=8787): Max retries exceeded with url: /dar/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002AA8BA46CC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
ERROR - 2024-03-27 17:53:01,005 - apiutil.py:131 -[apiutil:specification_yaml] - HTTPConnectionPool(host='127.0.0.1', port=8787): Max retries exceeded with url: /dar/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025983DB6E88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
ERROR - 2024-03-27 17:55:54,153 - apiutil.py:131 -[apiutil:specification_yaml] - HTTPConnectionPool(host='127.0.0.1', port=8787): Max retries exceeded with url: /dar/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DEF9CF6CC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
ERROR - 2024-03-27 17:59:09,580 - apiutil.py:131 -[apiutil:specification_yaml] - HTTPConnectionPool(host='127.0.0.1', port=8787): Max retries exceeded with url: /dar/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000015553C7DB48>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
ERROR - 2024-03-27 18:00:34,390 - apiutil.py:131 -[apiutil:specification_yaml] - HTTPConnectionPool(host='127.0.0.1', port=8787): Max retries exceeded with url: /dar/user/login (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002CF6B888B88>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
